name: Trivy Remote Scan

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types: [completed]

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub (required if the image is private)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Trivy scan directly on Docker Hub image (remote scan)
      - name: Trivy remote scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "xusonglin/fastapi-app:latest"
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: table
          timeout: 600s