name: Trivy Scan

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types: ["completed"]

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: docker pull xusonglin/fastapi-app:latest

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "xusonglin/fastapi-app:latest"
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          format: table
